[package]
name = "prophecy-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0"
borsh = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"